UNEXPECTED_NAME = 'Указано недопустимое имя для короткой ссылки'
TOO_MANY_ATTEMPTS = 'Было потрачено слишком много попыток на генерацию short_id'
URL_ALREADY_EXISTS = 'Предложенный вариант короткой ссылки уже существует.'
MUST_SET_REQUIRED_FIELD = '{must_set} является обязательным полем!'
REQUEST_IS_NONE = 'Отсутствует тело запроса'
URL_NOT_EXISTS = 'Указанный id не найден'
SHORT_ID_ALREADY_EXIST = 'Предложенный вариант короткой ссылки уже существует.'
BANNED_SYMBOLS_USED = 'Нельзя использовать запрещенные символы'
ORIGINAL_LINK = 'Ссылка на страницу'
CUSTOM_ID = 'Желаемая ссылка'
REQUIRED_FIELD = 'Обязательное поле!'
URLFIELD_ONLY = 'Поле для ссылки!'
ACCEPT = 'Добавить'
NOT_EXISTS_404 = 404
ERROR_400 = 400
CREATED_201 = 201
STATUS_OK_200 = 200
MAX_ORIGINAL_LENGTH = 256
MAX_SHORT_LENGTH = 16
SHORT_ID_BASE_LENGTH = 6
MAX_ATTEMPTS = 10
